name: Pipeline
on: 
  push: 
    branches:
    - feature/*
    - feature*
 
jobs: 
  build-dev:
    if: ${{ github.event.ref != 'refs/heads/master' || github.event.ref != 'refs/heads/main' }} && ${{ github.event.ref != 'refs/heads/develop' }}
    echo " build-dev "
  build-test:
    if: ${{ github.event.ref != 'refs/heads/master' || github.event.ref != 'refs/heads/main' }} && ${{ github.event.ref != 'refs/heads/develop' }}
    echo "build-test"
  build-stage:
    if: ${{ github.event.ref == 'refs/heads/develop' }}
    echo "build-stage"
  build-prod:
    if: ${{ github.event.ref == 'refs/heads/master' || github.event.ref == 'refs/heads/main' }}
    echo "build-prod"
  code-analysis:
    strategy:
      matrix:
        build-jobs: [build-dev,build-test,build-stage,build-prod]
    echo"code analysis"
        
  
