name: Pipeline
on: 
  workflow_dispatch:
  push:
    branches: feature/test
 
jobs: 
  build-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref != 'refs/heads/master' || github.event.ref != 'refs/heads/main' }} && ${{ github.event.ref != 'refs/heads/develop' }}
    steps:
      - run: echo "build-dev"
      
  build-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref != 'refs/heads/master' || github.event.ref != 'refs/heads/main' }} && ${{ github.event.ref != 'refs/heads/develop' }}
    steps:
       - run: echo "build-test"
       
  build-stage:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == 'refs/heads/develop' }}
    steps:
      - run: echo "build-stage"
      
  build-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == 'refs/heads/master' || github.event.ref == 'refs/heads/main' }}
    steps:
      - run: echo "build-prod"
      
  code-analysis:
    runs-on: ubuntu-latest
    needs: [build-dev,build-test,build-stage,build-prod]
    if: success('build-dev') && success('build-tes')
    steps:
      - run: echo "code analysis"
        
  
