name: compile
on: 
  workflow_dispatch:
  push: 
    branches:
    - feature/*
    - feature*
  pull_request:
    branches: 
    - develop
    - master
    - main
    - tags
jobs: 
  build-dev:
    runs-on: ubuntu-latest
    #if: ${{ github.event.ref != 'refs/heads/master' || github.event.ref != 'refs/heads/main' }} && ${{ github.event.ref != 'refs/heads/develop' }}
    if: ( github.event.ref != 'refs/heads/master' || github.event.ref != 'refs/heads/main' ) && ( github.event.ref != 'refs/heads/develop' )
    steps:
      - run: echo "dev build"
     
  build-test:
    runs-on: ubuntu-latest
    #if: ${{ github.event.ref != 'refs/heads/master' || github.event.ref != 'refs/heads/main' }} && ${{ github.event.ref != 'refs/heads/develop' }}
    if: ( github.event.ref != 'refs/heads/master' || github.event.ref != 'refs/heads/main' ) && ( github.event.ref != 'refs/heads/develop' )
    steps:
      - run: echo "test build"
      
  build-stage:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == 'refs/heads/develop' }}
    steps:
      - run: echo "stage"
      
  build-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == 'refs/heads/master' || github.event.ref == 'refs/heads/main' }}
    steps:
      - run: echo "prod"
      
  code-analysis:
    runs-on: ubuntu-latest
    needs: [build-dev,build-test,build-stage,build-prod]
    if: (success('build-dev') && success('build-test')) || 
        success('build-stage') ||
        success('build-prod')
    steps:
       - run: echo "sonar analysis"
  
