name: container
on:
  push:
    branches: [feature]

jobs:
   job1:
      runs-on: ubuntu-latest
      container: 
          image: node:14.16
      steps:
       - run: |
            node --version
            npm --version
      
