name: Maven GitHub Actions Sample

on: [push, pull_request]

jobs:

  build:
    
  
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}
        
    steps:
        
  
      - if: matrix.os == 'macOS-latest'
        run: |
          echo "ionic cordova platform add ios"
          echo "ionic cordova build ios"

      - if: matrix.os == 'windows-latest'
        run: |
          echo "ionic cordova platform add android"
          echo "ionic cordova build andro"
