# This workflow will build a Java project with Gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [1.6, 1.7, 1.8]
        
    steps:
      - uses: actions/checkout@v3
      
        if: matrix.java-version == '1.8'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: echo "chmod +x gradlew"

      - name: Build with Gradle
        run: echo "./gradlew build"

   
         
