# This workflow will build a Java project with Gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: echo "chmod +x gradlew"

    - name: Build with Gradle
      run: echo "./gradlew build"

    - name: Build and Push Docker Image
      uses: sindhu530/docker-build-push@v4
      with:
        image: sindhu530/demo-app
        registry: docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
         
