name: Java CI with Maven

on: 
  workflow_call:
    inputs:
      javaVersion:
           type: string
           required: true
      nodeVersion:
           type: string
           required: true
    

jobs:
  java11-node14:
   
    if: ${{ (inputs.javaVersion == '11' ) && (inputs.nodeVersion == '14') }} 
    runs-on: ubuntu-latest
    container: 
      #image: openjdk11-node14:v1.0
      image: openjdk:11

    steps:
    - name: Check-out project
      uses: actions/checkout@v1
    - name: install dependencies
      run: |
          mkdir artifact 
          cd artifact
          echo " mvn --batch-mode --update-snapshots package" > target.jar
          cd ..
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: artifact1
          path: ./
          
          
  java12-node18:
    
    #if: ${{ inputs.javaVersion == '12' }}
    if: ${{ (inputs.javaVersion == '12' ) && (inputs.nodeVersion == '18') }} 
    runs-on: ubuntu-latest
    container: 
      #image: openjdk12-node18:v1.0
      image: openjdk:12

    steps:
    - name: Check-out project
      uses: actions/checkout@v1
    - name: install dependencies
      run: |
          mkdir artifact 
          cd artifact
          echo " mvn --batch-mode --update-snapshots package" > target.jar
          cd ..
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: artifact2
          path: ./
          
 
  java17-node14:
   
    if: ${{ (inputs.javaVersion == '17' ) && (inputs.nodeVersion == '14') }} 
    runs-on: ubuntu-latest
    container: 
      #image: openjdk17-node14:v1.0
      image: openjdk:17

    steps:
    - name: print
      run: echo "openjdk17-node14:v1.0"
     
      
      
