name: pipelineInputs
on:
  workflow_call:
  
  
      outputs:
      
         pipelineType:
            value: "azstaticwebapp"
         language:
            value: "nodejs"
         nodeVersion:
            value: 16
         buildTool: 
            value: "npm"
         appName: 
            value: "abc"
         package: 
            value: true
            
         Files_or_folders_To_zip: 
            value: "[build,package.json]"
         deploymentFolderName: 
            value: "build"
            
         BUILD_image_name: 
            value: "stellantis-harbor.artifactory.intra.fcagroup.com/nodejs16-lts:v1.0.0"
         Deployment_image_name: 
            value: "stellantis-harbor.artifactory.intra.fcagroup.com/azure-swa:v1.0.0"
            
         rtDownload_AppKeys: 
            value: "12149-SP.zip"
         rtDownload_AppArtficat:
             value: ""
  
  
jobs:

  Environments:
    runs-on: [ ubuntu-latest]
    steps:
      - name: Dev Environment
        env:
          DEV_resourceGroup: "rg-12149-d-006"
          DEV_staticwebappName: "azapp-12149-d-006"
          DEV_env: "dev"
      - name: Stage Environment
        env:
          STAGE_resourceGroup: "rg-12149-d-006"
          STAGE_staticwebappName: "azapp-12149-d-006"
          STAGE_env: "stage"
      - name: Prod Environment
        env:
          PROD_resourceGroup: "rg-12149-d-006"
          PROD_staticwebappName: "azapp-12149-d-006"
          PROD_env: "stage"
    
        
