name: Pipeline1
on: 
  workflow_dispatch:
  push:
    branches: [feature/*, develop, main]
    
 
jobs: 
  build-dev:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'feature-') || !contains(github.ref, 'feature/') }}
    #if: contains(github.ref, 'feature-') || contains(github.ref, 'feature/')
    steps:
      - run: echo "build-dev"
      
  build-test:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'feature-') || contains(github.ref, 'feature/')
    steps:
       - run: echo "build-test"
       
  build-stage:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == 'refs/heads/develop' }}
    steps:
      - run: echo "build-stage"
      
  build-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == 'refs/heads/master' || github.event.ref == 'refs/heads/main' }}
    steps:
      - run: echo "build-prod"
      
  code-analysis:
    runs-on: ubuntu-latest
    needs: [build-dev,build-test,build-stage,build-prod]
    if: (contains(github.ref, 'feature/') && success('build-dev') && success('build-test')) || 
        (contains(github.ref, 'develop') && success('build-stage')) ||
        (contains(github.ref, 'main') && success('build-prod'))
    steps:
       - run: echo "sonar analysis"
