name: inputs
on:
  workflow_call:
  workflow_dispatch:
  
      outputs:
      
         pipelineType:
            value: "azstaticwebapp"
         language:
            value: "nodejs"
         nodeVersion:
            value: 16
         buildTool: 
            value: "npm"
         appName: 
            value: "abc"
         package: 
            value: true
            
         Files_or_folders_To_zip: 
            value: "[build,package.json]"
         deploymentFolderName: 
            value: "build"
            
         BUILD_image_name: 
            value: "stellantis-harbor.artifactory.intra.fcagroup.com/nodejs16-lts:v1.0.0"
         Deployment_image_name: 
            value: "stellantis-harbor.artifactory.intra.fcagroup.com/azure-swa:v1.0.0"
            
         rtDownload_AppKeys: 
            value: "12149-SP.zip"
         rtDownload_AppArtficat:
             value: ""
            
         changeNumber:
            value: "CHG1234567"
            
        
env:
  dev:
    resourceGroup: "rg-12149-d-006"
    staticwebappName: "azapp-12149-d-006"
    env: "dev"
  



  
                     
jobs:
  Dev_Environments:
    runs-on: [ ubuntu-latest]
    steps:
      - name: printing
        run: echo " print"
        env:
          resourceGroup: "rg-12149-d-006"
          staticwebappName: "azapp-12149-d-006"
          env: "dev"
        
