name: pipelineConfig
on:
  workflow_call:
  
jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
       - name: Input values
         run: |
           declare -A array
           array=( [pipelineType]="${{ needs.pipelineconfig.outputs.pipelineType }}"  
                   [language]="${{ needs.pipelineconfig.outputs.language }}" 
                   [nodeVersion]="${{ needs.pipelineconfig.outputs.nodeVersion }}"
                   [buildTool]="${{ needs.pipelineconfig.outputs.buildTool }}"
                   [BUILD_image_name]="${{ needs.pipelineconfig.outputs.BUILD_image_name }}"
                   [Deployment_image_name]="${{ needs.pipelineconfig.outputs.Deployment_image_name }}"
                   [appName]="${{ needs.pipelineconfig.outputs.appName }}" )
                   
          
