name: Run the Action on each commit
on:
  push:
    branches: feature
    
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run the Action
        #if: startsWith(github.ref, 'refs/heads/feature')
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          branch: "main"
          base: feature
          title: "auto PR from feature to main"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
