name: Automatic PR

on:
  push:
    branches:
      - feature

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
        
      - name: Raise PR 1
        id: demo-1
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch1"
          base: feature
          title: "demo for auto pr1"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
