name: Deployment
on:
  push:
    branches:
      - main
      - 'feature-*'
      - 'feature/*'
      
  workflow_dispatch:
 
jobs:
          
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        shell: pwsh
        run: Write-Host "test1"
