name: Deployment
on:
  push:
    branches:
      - main
      - 'feature-*'
      - 'feature/*'
      
  workflow_dispatch:
  
defaults:
  run:
    shell: pwsh
 
jobs:
  
  inputs:
     uses: sindhura530/github-workflows/.github/workflows/pipelineConfig.yml@main
     
  Dev_Deploy:
    if: contains(github.ref, 'feature-') || contains(github.ref, 'feature/')
    needs: inputs
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: ${{ needs.inputs.outputs.DEV_resourceGroup }}
      STATIC_WEBAPP_NAME: ${{ needs.inputs.outputs.DEV_staticwebappName }}
      ENV: ${{ needs.inputs.outputs.DEV_Env }}
    container: ubuntu
    continue-on-error: false
    steps:
      - name: Dev Deploy
        continue-on-error: false
        run: |
             echo "1: $RESOURCE_GROUP"
             echo "2: $STATIC_WEBAPP_NAME"
             echo "3: $ENV"
        
  Stage_Deploy:
    needs: inputs
    if: contains(github.ref, 'develop')
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: ${{ needs.inputs.outputs.STAGE_resourceGroup }}
      STATIC_WEBAPP_NAME: ${{ needs.inputs.outputs.STAGE_staticwebappName }}
      ENV: ${{ needs.inputs.outputs.STAGE_Env }}
    container: ubuntu
    continue-on-error: false
    steps:
      - name: Dev Deploy
        continue-on-error: false
        run: |
             echo "1: $RESOURCE_GROUP"
             echo "2: $STATIC_WEBAPP_NAME"
             echo "3: $ENV"

  Prod_Deploy:
    needs: inputs
    if: contains(github.ref, 'main') || contains(github.ref, 'master')
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: ${{ secrets.PROD_RESOURCEGROUP }}    
      STATIC_WEBAPP_NAME: ${{ secrets.PROD_STATICWEBAPPNAME }}
      ENV: ${{ secrets.PROD_ENV }}
    container: ubuntu
    continue-on-error: false
    
    steps:
      - name: Prod Deploy 
        continue-on-error: false
        
        run: |
            
             pwsh -command 'invoke-webrequest -Uri "https://raw.githubusercontent.com/sindhura530/github-workflows/main/README.md" -OutFile "Publish.md"'
             echo "1: $RESOURCE_GROUP"
             echo "2: $STATIC_WEBAPP_NAME"
             echo "3: $ENV"
             #echo "4: ${{ env.RESOURCE_GROUP}}"
            
