name: testing
on:
 workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      resourceGroup: "11111"
      staticwebappName: "azapp-11111"
      env: "dev"
    steps:
      - name: test
        if: ${{ env.resourceGroup == "11111" }} && ${{ env.staticwebappName == "azapp-11111" }} && ${{ env.env == "dev" }} 
        run: echo "dev"
