name: testing
on:
 workflow_dispatch:

jobs:

  Prod_Deploy:
    runs-on: ubuntu-latest
    env:
      resourceGroup: '11111'
      staticwebappName: 'azapp-11111'
      env: 'dev'
    container: ubuntu
    continue-on-error: false
    steps:
      - name: Dev Deploy
        if: github.event.ref == 'refs/heads/main' &&
         ${{ env.resourceGroup == '11111' }} && 
         ${{ env.staticwebappName == 'azapp-11111' }} && 
         ${{ env.env == 'dev' }} 
        continue-on-error: false
        shell: pwsh
        run: |
          echo "prod deploy"
