name: testing
on:
 workflow_dispatch:

jobs:
  
  Dev_Deploy:
    runs-on: ubuntu-latest
    env:
      resourceGroup: '11111'
      staticwebappName: 'azapp-11111'
      env: 'dev'
    container: ubuntu
    continue-on-error: false
    steps:
      - name: Dev Deploy
        if: github.event.ref == 'refs/heads/feature' &&
         ${{ env.resourceGroup == '11111' }} && 
         ${{ env.staticwebappName == 'azapp-11111' }} && 
         ${{ env.env == 'dev' }} 
        continue-on-error: false
        run: echo "Dev deploy"
        
  Stage_Deploy:
    runs-on: ubuntu-latest
    env:
      resourceGroup: '11111'
      staticwebappName: 'azapp-11111'
      env: 'stage'
    container: ubuntu
    continue-on-error: false
    steps:
      - name: Dev Deploy
        if: github.event.ref == 'refs/heads/develop' &&
         ${{ env.resourceGroup == '11111' }} && 
         ${{ env.staticwebappName == 'azapp-11111' }} && 
         ${{ env.env == 'dev' }} 
        continue-on-error: false
        run: echo "stage deploy"

  Prod_Deploy:
    runs-on: ubuntu-latest
    env:
      resourceGroup: '11111'
      staticwebappName: 'azapp-11111'
      env: 'production'
    container: ubuntu
    continue-on-error: false
    steps:
      - name: Dev Deploy
        if: github.event.ref == 'refs/heads/main' &&
         ${{ env.resourceGroup == '11111' }} && 
         ${{ env.staticwebappName == 'azapp-11111' }} && 
         ${{ env.env == 'production' }} 
        continue-on-error: false
        run: echo "prod deploy"
